model_checkpoint_path: /weights/MedViT_base_im1k.pth
save_checkpoint_dir: /homes/bhsu/2024_research/MedViT/models_all_checkpoints/final_checkpoints/
wandb_log_proj: MedViT_KNN_Eval
wandb_log_offline: true
data_flag: octmnist
strategy: ddp
num_epochs: 15
lr: 0.005
batch_size: 64
knn_config:
    k: 5
    log_every_n_steps: 1 # num knn logs
    max_train_batches: 200 # num batches used for validation 
every_n_train_steps: 50 # num steps per ckpt save
log_every_n_steps: 1 # log every n steps