model_checkpoint_path: /weights/MedViT_base_im1k.pth
save_checkpoint_dir: /homes/bhsu/2024_research/MedViT/models_all_checkpoints/test_lightning_checkpoints/
wandb_log_proj: MedViT_KNN_Eval
wandb_log_offline: true
data_flag: octmnist
strategy: ddp
num_epochs: 100
lr: 0.005
batch_size: 16
knn_config:
    k: 5
    log_every_n_steps: 1
    max_train_batches: 5
every_n_train_steps: 10
log_every_n_steps: 1
